

name: todo_sql
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.2.0
  path_provider: ^1.6.0
  cupertino_icons: ^0.1.3
  flutter_state_notifier: ^0.4.2
  freezed_annotation: ^0.7.1
  provider: ^4.1.3
  uuid: ^2.0.4
  analyzer: ^0.39.14
  shared_preferences: ^0.4.3
  process_run: ^0.10.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.10.9
  json_serializable: ^3.5.0
  build_runner: ^1.10.0

flutter:
  uses-material-design: true